import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import { LocationProvider } from "@/lib/LocationContext";
import "./globals.css"; // Global CSS
import "aos/dist/aos.css";

import AOSInit from "@/components/AOSInit";
import Footer from "@/components/Footer";

import "../../public/assets/css/owl.carousel.css"; // Local CSS files
import "../../public/assets/css/fontawesome-all.css";
import "../../public/assets/css/flaticon.css";
import "../../public/assets/css/meanmenu.css";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/video.min.css";
import "../../public/assets/css/animate.min.css";
import "../../public/assets/css/lightbox.css";
import "../../public/assets/css/progess.css";
import "../../public/assets/css/style.css";
import "../../public/assets/css/custom.css";
import "../../public/assets/css/responsive.css";
import "../../public/assets/css/colors/switch.css";
import "../../public/assets/css/code.css";

import Script from "next/script"; // Next.js Script component for external scripts
import { Inter } from "next/font/google";
// Initialize Google Font (optional)
const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Load CSS from public/assets/css via <link> */}
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/fontawesome-all.css" />
        <link rel="stylesheet" href="/assets/css/owl.carousel.css" />
        <link rel="stylesheet" href="/assets/css/animate.min.css" />
        <link rel="stylesheet" href="/assets/css/lightbox.css" />
        <link rel="stylesheet" href="/assets/css/video.min.css" />
        <link rel="stylesheet" href="/assets/css/flaticon.css" />
        <link rel="stylesheet" href="/assets/css/meanmenu.css" />
        <link rel="stylesheet" href="/assets/css/progess.css" />
        <link rel="stylesheet" href="/assets/css/style.css" />
        <link rel="stylesheet" href="/assets/css/code.css" />
        <link rel="stylesheet" href="/assets/css/custom.css" />
        <link rel="stylesheet" href="/assets/css/responsive.css" />
        <link rel="stylesheet" href="/assets/css/colors/switch.css" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
        <LocationProvider>
          <Navbar />
          <main>
            <AOSInit />
            {children}
            <Footer />
          </main>
        </LocationProvider>

        {/* ✅ JS from public assets */}
        <Script src="/assets/js/jquery-2.1.4.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/bootstrap.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/owl.carousel.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/popper.min.js" />
        <Script src="/assets/js/jarallax.js" />
        <Script src="/assets/js/jquery.magnific-popup.min.js" />
        <Script src="/assets/js/lightbox.js" />
        <Script src="/assets/js/jquery.meanmenu.js" />
        <Script src="/assets/js/scrollreveal.min.js" />
        <Script src="/assets/js/jquery.counterup.min.js" />
        <Script src="/assets/js/waypoints.min.js" />
        <Script src="/assets/js/jquery-ui.js" />
        <Script src="/assets/js/gmap3.min.js" />
        <Script src="/assets/js/switch.js" />
        <Script src="/assets/js/Script.js" defer />
        <Script
          src="https://maps.google.com/maps/api/js?key=AIzaSyC61_QVqt9LAhwFdlQmsNwi5aUJy9B2SyA"
        />
      </body>
    </html>
  );
}

